name: Testing

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt a secret passphrase
        run: "hello from test.yml"
      #  run: ./.github/workflows/decrypt_secret.sh
      #  env:
      #    SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      #- name: Test printing your secret (Remove this step in production)
      #  run: cat $HOME/secrets/my_secret.json
